name: ${project.artifactId}
description: ${project.description}
version: ${project.version}
author: zPedroo_
main: com.zpedroo.mcmmoaddon.mcMMOAddon
depend: [mcMMO, ActionBarAPI, nChat, PlaceholderAPI]